# Generated by Django 2.1.7 on 2019-04-13 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferences', models.CharField(choices=[('AT', 'Arts & Theatre'), ('F', 'Film'), ('M', 'Miscellaneous'), ('Musice', 'Music'), ('S', 'Sports'), ('Undefined', 'Undefined'), ('D', 'Donation'), ('ES', 'Event Style'), ('G', 'Group'), ('I', 'Individual'), ('Merchandise', 'Merchandise'), ('N', 'Nonticket'), ('P', 'Parking'), ('T', 'Transportation'), ('U', 'Upsell'), ('V', 'Venue Based')], max_length=120)),
                ('genre', models.CharField(choices=[('KnvZfZ7vAee', 'R&B'), ('KnvZfZ7vAv1', 'Hip-Hop/Rap'), ('KnvZfZ7vAe1', 'Comedy'), ('KnvZfZ7v7nJ', 'Classical'), ('KnvZfZ7vAvE', 'Jazz'), ('KnvZfZ7vAk1', 'Foreign'), ('KnvZfZ7vAvF', 'Dance/Electronic'), ('KnvZfZ7vAkA', 'Comedy'), ('KnvZfZ7vAkd', 'Animation'), ('KnvZfZ7vAkJ', 'Music'), ('KnvZfZ7vAka', 'Miscellaneous'), ('KnvZfZ7vAk', 'Family'), ('KnvZfZ7v7ld', 'Miscellaneous Theatre'), ('KnvZfZ7v7l1', 'Theatre')], max_length=120)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
