# Generated by Django 2.1.7 on 2019-04-13 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='uid',
            field=models.CharField(default='null', max_length=100, unique=True),
        ),
    ]
