# Generated by Django 2.1.7 on 2019-04-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190412_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='preferences',
            field=models.CharField(choices=[('Arts & Theatre', 'Arts & Theatre'), ('Film', 'Film'), ('Miscellaneous', 'Miscellaneous'), ('Music', 'Music'), ('Sports', 'Sports'), ('Undefined', 'Undefined'), ('Donation', 'Donation'), ('Event Style', 'Event Style'), ('Group', 'Group'), ('Individual', 'Individual'), ('Merchandise', 'Merchandise'), ('Nonticket', 'Nonticket'), ('Parking', 'Parking'), ('Transportation', 'Transportation'), ('Upsell', 'Upsell'), ('Venue Based', 'Venue Based')], max_length=120),
        ),
    ]
